coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:  # Applies to new PR patches
      default:
        target: 90%  # Ensure new code has at least 90% coverage
        threshold: 0%  # No drop allowed
    changes:  # Applies to changed files in a PR
      default:
        target: 85%    

comment:
  layout: "condensed_header, diff, flags, components"
  
component_management:
  individual_components:
    - component_id: api-calculator  # this is an identifier that should not be changed
      name: calculator  # this is a display name, and can be changed freely
      paths:
        - api/calculator/
    - component_id: api-smiles  # this is an identifier that should not be changed
      name: smiles  # this is a display name, and can be changed freely
      paths:
        - api/smiles/
