name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'     
    - name: Install dependencies
      run: |
        pip install --index-url https://rospypi.github.io/simple/ actionlib || echo "Skipping actionlib pip installation"
        pip install -r api/requirements.txt || echo "Skipping missing dependencies"  
        pip install pytest pytest-cov 
    - name: Run tests and collect coverage
      run: pytest --cov=api.calculator --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}